# Generated by Django 4.2.6 on 2024-11-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_delete_ainazandege_remove_chatmessage_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatejaWote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaKamiliLaMteja', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Kamili La Mteja')),
                ('SimuYaMteja', models.IntegerField(blank=True, null=True, verbose_name='Namba Ya Simu Ya Mteja')),
                ('EmailYaMteja', models.EmailField(blank=True, max_length=500, null=True, verbose_name='Email Ya Mteja')),
                ('Mahali', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mahali Anapoishi')),
                ('MaelezoYaMteja', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Maelezo Ya Mteja')),
                ('KiasiAnachokopa', models.IntegerField(blank=True, null=True, verbose_name='Kiasi Kiasi Anachokopa')),
                ('RejeshoKwaSiku', models.IntegerField(blank=True, null=True, verbose_name='Rejesho Kwa Siku')),
                ('JumlaYaDeni', models.IntegerField(blank=True, null=True, verbose_name='Jumla Ya Deni Analodaiwa')),
                ('Riba', models.IntegerField(blank=True, null=True, verbose_name='Riba')),
                ('PichaYaMteja', models.ImageField(blank=True, null=True, upload_to='media/PichaZaVyakula/', verbose_name='Picha Ya Mteja')),
                ('Ni_Mteja_Hai', models.BooleanField(blank=True, default=True, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Wateja Wote',
            },
        ),
        migrations.CreateModel(
            name='WatejaWoteCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaKamiliLaMteja', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Kamili La Mteja')),
                ('ordered', models.BooleanField(default=False)),
                ('total_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Kiasi Alicholipa')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'WatejaWote  Cart',
            },
        ),
        migrations.CreateModel(
            name='WatejaWoteCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JinaKamiliLaMteja', models.CharField(blank=True, max_length=500, null=True, verbose_name='Jina Kamili La Mteja')),
                ('KiasiChaRejeshoChaSiku', models.FloatField(blank=True, default=0, null=True)),
                ('KiasiChaFainiChaSiku', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Mteja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.watejawote')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.watejawotecart')),
            ],
            options={
                'verbose_name_plural': 'WatejaWote  Cart Items',
            },
        ),
    ]
