# Generated by Django 4.2.6 on 2024-11-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_watejawote_watejawotecart_watejawotecartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='watejawote',
            name='AmesajiliwaNa',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Amesajiliwa Na ?'),
        ),
    ]
