# Generated by Django 4.2.6 on 2024-11-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_watejawote_kiasialicholipa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watejawote',
            name='JumlaYaDeni',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Jumla Ya Deni Analodaiwa'),
        ),
        migrations.AlterField(
            model_name='watejawote',
            name='KiasiAlicholipa',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Alicholipa Mpaka Sasa'),
        ),
        migrations.AlterField(
            model_name='watejawote',
            name='KiasiAnachokopa',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Kiasi Kiasi Anachokopa'),
        ),
        migrations.AlterField(
            model_name='watejawote',
            name='RejeshoKwaSiku',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rejesho Kwa Siku'),
        ),
        migrations.AlterField(
            model_name='watejawote',
            name='Riba',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Riba'),
        ),
    ]
